#include "FFXIVResources.h"

bool FFXIVResources::IsKnownSkill(int skillid) {
	switch (skillid) {
		case 0x1: return true;
		case 0x3: return true;
		case 0x5: return true;
		case 0x9: return true;
		case 0xa: return true;
		case 0xb: return true;
		case 0xc: return true;
		case 0xd: return true;
		case 0xe: return true;
		case 0xf: return true;
		case 0x10: return true;
		case 0x11: return true;
		case 0x12: return true;
		case 0x13: return true;
		case 0x14: return true;
		case 0x15: return true;
		case 0x16: return true;
		case 0x17: return true;
		case 0x18: return true;
		case 0x19: return true;
		case 0x1a: return true;
		case 0x1b: return true;
		case 0x1c: return true;
		case 0x1d: return true;
		case 0x1e: return true;
		case 0x1f: return true;
		case 0x20: return true;
		case 0x21: return true;
		case 0x22: return true;
		case 0x23: return true;
		case 0x24: return true;
		case 0x25: return true;
		case 0x26: return true;
		case 0x27: return true;
		case 0x28: return true;
		case 0x29: return true;
		case 0x2a: return true;
		case 0x2b: return true;
		case 0x2c: return true;
		case 0x2d: return true;
		case 0x2e: return true;
		case 0x2f: return true;
		case 0x30: return true;
		case 0x31: return true;
		case 0x32: return true;
		case 0x33: return true;
		case 0x34: return true;
		case 0x35: return true;
		case 0x36: return true;
		case 0x37: return true;
		case 0x38: return true;
		case 0x39: return true;
		case 0x3a: return true;
		case 0x3b: return true;
		case 0x3c: return true;
		case 0x3d: return true;
		case 0x3e: return true;
		case 0x3f: return true;
		case 0x40: return true;
		case 0x41: return true;
		case 0x42: return true;
		case 0x43: return true;
		case 0x44: return true;
		case 0x45: return true;
		case 0x46: return true;
		case 0x47: return true;
		case 0x48: return true;
		case 0x49: return true;
		case 0x4a: return true;
		case 0x4b: return true;
		case 0x4c: return true;
		case 0x4d: return true;
		case 0x4e: return true;
		case 0x4f: return true;
		case 0x50: return true;
		case 0x51: return true;
		case 0x52: return true;
		case 0x53: return true;
		case 0x54: return true;
		case 0x55: return true;
		case 0x56: return true;
		case 0x57: return true;
		case 0x58: return true;
		case 0x59: return true;
		case 0x5a: return true;
		case 0x5b: return true;
		case 0x5c: return true;
		case 0x5d: return true;
		case 0x5e: return true;
		case 0x5f: return true;
		case 0x60: return true;
		case 0x61: return true;
		case 0x62: return true;
		case 0x63: return true;
		case 0x64: return true;
		case 0x65: return true;
		case 0x66: return true;
		case 0x67: return true;
		case 0x68: return true;
		case 0x69: return true;
		case 0x6a: return true;
		case 0x6b: return true;
		case 0x6c: return true;
		case 0x6d: return true;
		case 0x6e: return true;
		case 0x6f: return true;
		case 0x70: return true;
		case 0x71: return true;
		case 0x72: return true;
		case 0x73: return true;
		case 0x74: return true;
		case 0x75: return true;
		case 0x76: return true;
		case 0x77: return true;
		case 0x78: return true;
		case 0x79: return true;
		case 0x7a: return true;
		case 0x7b: return true;
		case 0x7c: return true;
		case 0x7d: return true;
		case 0x7e: return true;
		case 0x7f: return true;
		case 0x80: return true;
		case 0x81: return true;
		case 0x82: return true;
		case 0x83: return true;
		case 0x84: return true;
		case 0x85: return true;
		case 0x86: return true;
		case 0x87: return true;
		case 0x88: return true;
		case 0x89: return true;
		case 0x8a: return true;
		case 0x8b: return true;
		case 0x8c: return true;
		case 0x8d: return true;
		case 0x8e: return true;
		case 0x8f: return true;
		case 0x90: return true;
		case 0x91: return true;
		case 0x92: return true;
		case 0x93: return true;
		case 0x94: return true;
		case 0x95: return true;
		case 0x96: return true;
		case 0x97: return true;
		case 0x98: return true;
		case 0x99: return true;
		case 0x9a: return true;
		case 0x9b: return true;
		case 0x9c: return true;
		case 0x9d: return true;
		case 0x9e: return true;
		case 0x9f: return true;
		case 0xa0: return true;
		case 0xa1: return true;
		case 0xa2: return true;
		case 0xa3: return true;
		case 0xa4: return true;
		case 0xa5: return true;
		case 0xa6: return true;
		case 0xa7: return true;
		case 0xa8: return true;
		case 0xa9: return true;
		case 0xaa: return true;
		case 0xab: return true;
		case 0xac: return true;
		case 0xad: return true;
		case 0xae: return true;
		case 0xaf: return true;
		case 0xb0: return true;
		case 0xb1: return true;
		case 0xb2: return true;
		case 0xb3: return true;
		case 0xb4: return true;
		case 0xb5: return true;
		case 0xb6: return true;
		case 0xb7: return true;
		case 0xb8: return true;
		case 0xb9: return true;
		case 0xba: return true;
		case 0xbb: return true;
		case 0xbc: return true;
		case 0xbd: return true;
		case 0xbe: return true;
		case 0xbf: return true;
		case 0xc5: return true;
		case 0xc6: return true;
		case 0xc7: return true;
		case 0xc8: return true;
		case 0xc9: return true;
		case 0xca: return true;
		case 0xcb: return true;
		case 0xcc: return true;
		case 0xcd: return true;
		case 0xce: return true;
		case 0xcf: return true;
		case 0xd0: return true;
		case 0x137: return true;
		case 0x138: return true;
		case 0x156: return true;
		case 0x17a: return true;
		case 0x1aa: return true;
		case 0x1ab: return true;
		case 0x1ac: return true;
		case 0x1ad: return true;
		case 0x1ae: return true;
		case 0x1af: return true;
		case 0x1ff: return true;
		case 0x248: return true;
		case 0x279: return true;
		case 0x27a: return true;
		case 0x27b: return true;
		case 0x27c: return true;
		case 0x27d: return true;
		case 0x27e: return true;
		case 0x27f: return true;
		case 0x280: return true;
		case 0x2ab: return true;
		case 0x2b6: return true;
		case 0x2d4: return true;
		case 0x2df: return true;
		case 0x313: return true;
		case 0x314: return true;
		case 0x315: return true;
		case 0x316: return true;
		case 0x317: return true;
		case 0x318: return true;
		case 0x319: return true;
		case 0x31a: return true;
		case 0x31b: return true;
		case 0x31c: return true;
		case 0x31d: return true;
		case 0x31e: return true;
		case 0x31f: return true;
		case 0x320: return true;
		case 0x321: return true;
		case 0x322: return true;
		case 0x323: return true;
		case 0x324: return true;
		case 0x325: return true;
		case 0x326: return true;
		case 0x327: return true;
		case 0x328: return true;
		case 0x329: return true;
		case 0x32a: return true;
		case 0x32b: return true;
		case 0x331: return true;
		case 0x332: return true;
		case 0x333: return true;
		case 0x334: return true;
		case 0x335: return true;
		case 0x336: return true;
		case 0x337: return true;
		case 0x338: return true;
		case 0x339: return true;
		case 0x33a: return true;
		case 0x33b: return true;
		case 0x33c: return true;
		case 0x35b: return true;
		case 0x3dc: return true;
		case 0x3de: return true;
		case 0x437: return true;
		case 0x442: return true;
		case 0x4bc: return true;
		case 0x4ce: return true;
		case 0x4da: return true;
		case 0x59c: return true;
		case 0x5cd: return true;
		case 0x5fe: return true;
		case 0x631: return true;
		case 0x64a: return true;
		case 0x67b: return true;
		case 0x72c: return true;
		case 0x7da: return true;
		case 0x80a: return true;
		case 0x874: return true;
		case 0x875: return true;
		case 0x89c: return true;
		case 0x8c0: return true;
		case 0x8c1: return true;
		case 0x8c2: return true;
		case 0x8c3: return true;
		case 0x8c4: return true;
		case 0x8c5: return true;
		case 0x8c6: return true;
		case 0x8c7: return true;
		case 0x8c8: return true;
		case 0x8c9: return true;
		case 0x8ca: return true;
		case 0x8cb: return true;
		case 0x8cc: return true;
		case 0x8ce: return true;
		case 0x8cf: return true;
		case 0x8d0: return true;
		case 0x8d1: return true;
		case 0x8d2: return true;
		case 0x8d3: return true;
		case 0x8d4: return true;
		case 0x8d5: return true;
		case 0x8d6: return true;
		case 0x8d7: return true;
		case 0x8d8: return true;
		case 0x8d9: return true;
		case 0x8da: return true;
		case 0x8db: return true;
		case 0x8dc: return true;
		case 0x8dd: return true;
		case 0x8de: return true;
		case 0x8df: return true;
		case 0x8e0: return true;
		case 0x923: return true;
		case 0x943: return true;
		case 0x964: return true;
		case 0x986: return true;
		case 0x993: return true;
		case 0x9ff: return true;
		case 0xb30: return true;
		case 0xb31: return true;
		case 0xb32: return true;
		case 0xb33: return true;
		case 0xb34: return true;
		case 0xb35: return true;
		case 0xb36: return true;
		case 0xb37: return true;
		case 0xb38: return true;
		case 0xb39: return true;
		case 0xb3a: return true;
		case 0xb3b: return true;
		case 0xb3c: return true;
		case 0xb3d: return true;
		case 0xb3e: return true;
		case 0xb3f: return true;
		case 0xb40: return true;
		case 0xb41: return true;
		case 0xb42: return true;
		case 0xb43: return true;
		case 0xb44: return true;
		case 0xb45: return true;
		case 0xb46: return true;
		case 0xb47: return true;
		case 0xb48: return true;
		case 0xb49: return true;
		case 0xb4a: return true;
		case 0xb4b: return true;
		case 0xb4c: return true;
		case 0xb91: return true;
		case 0xcb1: return true;
		case 0xd0e: return true;
		case 0xd5b: return true;
		case 0xd9f: return true;
		case 0xdd2: return true;
		case 0xdd3: return true;
		case 0xdd4: return true;
		case 0xdd5: return true;
		case 0xdd6: return true;
		case 0xdd7: return true;
		case 0xdd8: return true;
		case 0xdd9: return true;
		case 0xdda: return true;
		case 0xddb: return true;
		case 0xddc: return true;
		case 0xddd: return true;
		case 0xdde: return true;
		case 0xddf: return true;
		case 0xde0: return true;
		case 0xde1: return true;
		case 0xde2: return true;
		case 0xde3: return true;
		case 0xde4: return true;
		case 0xde5: return true;
		case 0xde6: return true;
		case 0xde7: return true;
		case 0xde8: return true;
		case 0xde9: return true;
		case 0xdea: return true;
		case 0xdeb: return true;
		case 0xdec: return true;
		case 0xded: return true;
		case 0xdee: return true;
		case 0xdef: return true;
		case 0xdf0: return true;
		case 0xdf1: return true;
		case 0xdf2: return true;
		case 0xdf3: return true;
		case 0xdf4: return true;
		case 0xdf5: return true;
		case 0xdf6: return true;
		case 0xdf7: return true;
		case 0xdf8: return true;
		case 0xdf9: return true;
		case 0xdfa: return true;
		case 0xdfb: return true;
		case 0xdfc: return true;
		case 0xdfd: return true;
		case 0xdfe: return true;
		case 0xdff: return true;
		case 0xe00: return true;
		case 0xe01: return true;
		case 0xe02: return true;
		case 0xe03: return true;
		case 0xe04: return true;
		case 0xe05: return true;
		case 0xe06: return true;
		case 0xe07: return true;
		case 0xe08: return true;
		case 0xe09: return true;
		case 0xe0a: return true;
		case 0xe0b: return true;
		case 0xe0c: return true;
		case 0xe0d: return true;
		case 0xe0e: return true;
		case 0xe0f: return true;
		case 0xe10: return true;
		case 0xe11: return true;
		case 0xe12: return true;
		case 0xe13: return true;
		case 0xe14: return true;
		case 0xe15: return true;
		case 0xe16: return true;
		case 0xe17: return true;
		case 0xe18: return true;
		case 0xe19: return true;
		case 0xe1a: return true;
		case 0xe1b: return true;
		case 0xe1c: return true;
		case 0xe1d: return true;
		case 0xe1e: return true;
		case 0xe1f: return true;
		case 0xe20: return true;
		case 0xe21: return true;
		case 0xe22: return true;
		case 0xe23: return true;
		case 0xe24: return true;
		case 0xe25: return true;
		case 0xe26: return true;
		case 0xe27: return true;
		case 0xe28: return true;
		case 0xe29: return true;
		case 0xe2a: return true;
		case 0xe2b: return true;
		case 0xe2c: return true;
		case 0xe2d: return true;
		case 0xe2e: return true;
		case 0xe2f: return true;
		case 0xe30: return true;
		case 0xe31: return true;
		case 0xe32: return true;
		case 0xe33: return true;
		case 0xe34: return true;
		case 0xe35: return true;
		case 0xe36: return true;
		case 0xe37: return true;
		case 0xe38: return true;
		case 0xe39: return true;
		case 0xe3a: return true;
		case 0xe3b: return true;
		case 0xe80: return true;
		case 0xe81: return true;
		case 0xe82: return true;
		case 0xeb1: return true;
		case 0xfdc: return true;
		case 0x108e: return true;
		case 0x108f: return true;
		case 0x1090: return true;
		case 0x1091: return true;
		case 0x1092: return true;
		case 0x1093: return true;
		case 0x1094: return true;
		case 0x1095: return true;
		case 0x1096: return true;
		case 0x1097: return true;
		case 0x1098: return true;
		case 0x10a6: return true;
		case 0x1131: return true;
		case 0x1132: return true;
		case 0x1133: return true;
		case 0x1134: return true;
		case 0x1135: return true;
		case 0x1136: return true;
		case 0x11c7: return true;
		case 0x11c8: return true;
		case 0x11c9: return true;
		case 0x11ca: return true;
		case 0x11cb: return true;
		case 0x11cc: return true;
		case 0x11cd: return true;
		case 0x11ce: return true;
		case 0x11cf: return true;
		case 0x11d0: return true;
		case 0x11e8: return true;
		case 0x128b: return true;
		case 0x1326: return true;
		case 0x1327: return true;
		case 0x132c: return true;
		case 0x13cc: return true;
		case 0x13cf: return true;
		case 0x1598: return true;
		case 0x16d3: return true;
		case 0x1731: return true;
		case 0x1734: return true;
		case 0x1cd6: return true;
		case 0x1cd7: return true;
		case 0x1cd8: return true;
		case 0x1cd9: return true;
		case 0x1cda: return true;
		case 0x1cdb: return true;
		case 0x1cdc: return true;
		case 0x1cdd: return true;
		case 0x1cde: return true;
		case 0x1cdf: return true;
		case 0x1ce0: return true;
		case 0x1ce1: return true;
		case 0x1ce2: return true;
		case 0x1ce3: return true;
		case 0x1ce4: return true;
		case 0x1ce5: return true;
		case 0x1ce6: return true;
		case 0x1ce7: return true;
		case 0x1ce8: return true;
		case 0x1ce9: return true;
		case 0x1cea: return true;
		case 0x1ceb: return true;
		case 0x1ced: return true;
		case 0x1cee: return true;
		case 0x1cef: return true;
		case 0x1cf0: return true;
		case 0x1cf1: return true;
		case 0x1cf2: return true;
		case 0x1cf6: return true;
		case 0x1cf7: return true;
		case 0x1cf8: return true;
		case 0x1cf9: return true;
		case 0x1cfa: return true;
		case 0x1cfb: return true;
		case 0x1cfc: return true;
		case 0x1cfd: return true;
		case 0x1cfe: return true;
		case 0x1cff: return true;
		case 0x1d00: return true;
		case 0x1d01: return true;
		case 0x1d02: return true;
		case 0x1d03: return true;
		case 0x1d04: return true;
		case 0x1d05: return true;
		case 0x1d06: return true;
		case 0x1d07: return true;
		case 0x1d08: return true;
		case 0x1d09: return true;
		case 0x1d0a: return true;
		case 0x1d0b: return true;
		case 0x1d0c: return true;
		case 0x1d0d: return true;
		case 0x1d0e: return true;
		case 0x1d0f: return true;
		case 0x1d10: return true;
		case 0x1d11: return true;
		case 0x1d12: return true;
		case 0x1d13: return true;
		case 0x1d14: return true;
		case 0x1d15: return true;
		case 0x1d18: return true;
		case 0x1d19: return true;
		case 0x1d1a: return true;
		case 0x1d35: return true;
		case 0x1d36: return true;
		case 0x1d37: return true;
		case 0x1d38: return true;
		case 0x1d39: return true;
		case 0x1d3a: return true;
		case 0x1d3b: return true;
		case 0x1d3c: return true;
		case 0x1d3d: return true;
		case 0x1d3e: return true;
		case 0x1d3f: return true;
		case 0x1d40: return true;
		case 0x1d41: return true;
		case 0x1d42: return true;
		case 0x1d43: return true;
		case 0x1d44: return true;
		case 0x1d46: return true;
		case 0x1d47: return true;
		case 0x1d48: return true;
		case 0x1d49: return true;
		case 0x1d4a: return true;
		case 0x1d4b: return true;
		case 0x1d4c: return true;
		case 0x1d4d: return true;
		case 0x1d4e: return true;
		case 0x1d4f: return true;
		case 0x1d50: return true;
		case 0x1d51: return true;
		case 0x1d52: return true;
		case 0x1d53: return true;
		case 0x1d54: return true;
		case 0x1d55: return true;
		case 0x1d56: return true;
		case 0x1d57: return true;
		case 0x1d58: return true;
		case 0x1d59: return true;
		case 0x1d5a: return true;
		case 0x1d5b: return true;
		case 0x1d5c: return true;
		case 0x1d5d: return true;
		case 0x1d5e: return true;
		case 0x1d5f: return true;
		case 0x1d60: return true;
		case 0x1d61: return true;
		case 0x1d62: return true;
		case 0x1d63: return true;
		case 0x1d64: return true;
		case 0x1d65: return true;
		case 0x1d66: return true;
		case 0x1d67: return true;
		case 0x1d68: return true;
		case 0x1d69: return true;
		case 0x1d6a: return true;
		case 0x1d6b: return true;
		case 0x1d6c: return true;
		case 0x1d6d: return true;
		case 0x1d6e: return true;
		case 0x1d6f: return true;
		case 0x1d70: return true;
		case 0x1d71: return true;
		case 0x1d72: return true;
		case 0x1d73: return true;
		case 0x1d74: return true;
		case 0x1d75: return true;
		case 0x1d76: return true;
		case 0x1d77: return true;
		case 0x1d78: return true;
		case 0x1d79: return true;
		case 0x1d7a: return true;
		case 0x1d7b: return true;
		case 0x1d7c: return true;
		case 0x1d7d: return true;
		case 0x1d7e: return true;
		case 0x1d7f: return true;
		case 0x1d80: return true;
		case 0x1d81: return true;
		case 0x1d82: return true;
		case 0x1d83: return true;
		case 0x1d84: return true;
		case 0x1d85: return true;
		case 0x1d86: return true;
		case 0x1d87: return true;
		case 0x1d88: return true;
		case 0x1d89: return true;
		case 0x1d8a: return true;
		case 0x1d8b: return true;
		case 0x1d8c: return true;
		case 0x1d8d: return true;
		case 0x1d8e: return true;
		case 0x1d8f: return true;
		case 0x1d90: return true;
		case 0x1d91: return true;
		case 0x1d92: return true;
		case 0x1d93: return true;
		case 0x1d94: return true;
		case 0x1eb5: return true;
		case 0x1eb6: return true;
		case 0x1eb7: return true;
		case 0x1eb8: return true;
		case 0x1eb9: return true;
		case 0x1eba: return true;
		case 0x1ebb: return true;
		case 0x1ebc: return true;
		case 0x1ebd: return true;
		case 0x2084: return true;
		case 0x228a: return true;
		case 0x2290: return true;
		case 0x2291: return true;
		case 0x2292: return true;
		case 0x2337: return true;
		case 0xf540a: return true;
		case 0xf540e: return true;
		case 0xf540f: return true;
		case 0xf5428: return true;
	}
	return false;
}

std::string FFXIVResources::GetSkillName(int skillid) {
	switch (skillid) {
		case 0x1: return "malefic";
		case 0x3: return "sprint";
		case 0x5: return "teleport";
		case 0x9: return "fast blade";
		case 0xa: return "rampart";
		case 0xb: return "savage blade";
		case 0xc: return "convalescence";
		case 0xd: return "awareness";
		case 0xe: return "flash";
		case 0xf: return "riot blade";
		case 0x10: return "shield bash";
		case 0x11: return "sentinel";
		case 0x12: return "provoke";
		case 0x13: return "tempered will";
		case 0x14: return "fight or flight";
		case 0x15: return "rage of halone";
		case 0x16: return "bulwark";
		case 0x17: return "circle of scorn";
		case 0x18: return "shield lob";
		case 0x19: return "shield swipe";
		case 0x1a: return "sword oath";
		case 0x1b: return "cover";
		case 0x1c: return "shield oath";
		case 0x1d: return "spirits within";
		case 0x1e: return "hallowed ground";
		case 0x1f: return "heavy swing";
		case 0x20: return "foresight";
		case 0x21: return "fracture";
		case 0x22: return "bloodbath";
		case 0x23: return "skull sunder";
		case 0x24: return "mercy stroke";
		case 0x25: return "maim";
		case 0x26: return "berserk";
		case 0x27: return "brutal swing";
		case 0x28: return "thrill of battle";
		case 0x29: return "overpower";
		case 0x2a: return "storm's path";
		case 0x2b: return "holmgang";
		case 0x2c: return "vengeance";
		case 0x2d: return "storm's eye";
		case 0x2e: return "tomahawk";
		case 0x2f: return "butcher's block";
		case 0x30: return "defiance";
		case 0x31: return "inner beast";
		case 0x32: return "unchained";
		case 0x33: return "steel cyclone";
		case 0x34: return "infuriate";
		case 0x35: return "bootshine";
		case 0x36: return "true strike";
		case 0x37: return "featherfoot";
		case 0x38: return "snap punch";
		case 0x39: return "second wind";
		case 0x3a: return "haymaker";
		case 0x3b: return "internal release";
		case 0x3c: return "fists of earth";
		case 0x3d: return "twin snakes";
		case 0x3e: return "arm of the destroyer";
		case 0x3f: return "fists of fire";
		case 0x40: return "steel peak";
		case 0x41: return "mantra";
		case 0x42: return "demolish";
		case 0x43: return "howling fist";
		case 0x44: return "touch of death";
		case 0x45: return "perfect balance";
		case 0x46: return "rockbreaker";
		case 0x47: return "shoulder tackle";
		case 0x48: return "one ilm punch";
		case 0x49: return "fists of wind";
		case 0x4a: return "dragon kick";
		case 0x4b: return "true thrust";
		case 0x4c: return "feint";
		case 0x4d: return "keen flurry";
		case 0x4e: return "vorpal thrust";
		case 0x4f: return "heavy thrust";
		case 0x50: return "invigorate";
		case 0x51: return "impulse drive";
		case 0x52: return "leg sweep";
		case 0x53: return "life surge";
		case 0x54: return "full thrust";
		case 0x55: return "blood for blood";
		case 0x56: return "doom spike";
		case 0x57: return "disembowel";
		case 0x58: return "chaos thrust";
		case 0x59: return "ring of thorns";
		case 0x5a: return "piercing talon";
		case 0x5b: return "phlebotomize";
		case 0x5c: return "jump";
		case 0x5d: return "power surge";
		case 0x5e: return "elusive jump";
		case 0x5f: return "spineshatter dive";
		case 0x60: return "dragonfire dive";
		case 0x61: return "heavy shot";
		case 0x62: return "straight shot";
		case 0x63: return "hawk's eye";
		case 0x64: return "venomous bite";
		case 0x65: return "raging strikes";
		case 0x66: return "flaming arrow";
		case 0x67: return "misery's end";
		case 0x68: return "quelling strikes";
		case 0x69: return "swiftsong";
		case 0x6a: return "quick nock";
		case 0x6b: return "barrage";
		case 0x6c: return "shadowbind";
		case 0x6d: return "blunt arrow";
		case 0x6e: return "bloodletter";
		case 0x6f: return "wide volley";
		case 0x70: return "repelling shot";
		case 0x71: return "windbite";
		case 0x72: return "mage's ballad";
		case 0x73: return "foe requiem";
		case 0x74: return "army's paeon";
		case 0x75: return "rain of death";
		case 0x76: return "battle voice";
		case 0x77: return "stone";
		case 0x78: return "cure";
		case 0x79: return "aero";
		case 0x7a: return "cleric stance";
		case 0x7b: return "protect";
		case 0x7c: return "medica";
		case 0x7d: return "raise";
		case 0x7e: return "esuna";
		case 0x7f: return "stone ii";
		case 0x80: return "repose";
		case 0x81: return "stoneskin";
		case 0x82: return "shroud of saints";
		case 0x83: return "cure iii";
		case 0x84: return "aero ii";
		case 0x85: return "medica ii";
		case 0x86: return "fluid aura";
		case 0x87: return "cure ii";
		case 0x88: return "presence of mind";
		case 0x89: return "regen";
		case 0x8a: return "divine seal";
		case 0x8b: return "holy";
		case 0x8c: return "benediction";
		case 0x8d: return "fire";
		case 0x8e: return "blizzard";
		case 0x8f: return "surecast";
		case 0x90: return "thunder";
		case 0x91: return "sleep";
		case 0x92: return "blizzard ii";
		case 0x93: return "fire ii";
		case 0x94: return "thunder ii";
		case 0x95: return "transpose";
		case 0x96: return "swiftcast";
		case 0x97: return "lethargy";
		case 0x98: return "fire iii";
		case 0x99: return "thunder iii";
		case 0x9a: return "blizzard iii";
		case 0x9b: return "aetherial manipulation";
		case 0x9c: return "scathe";
		case 0x9d: return "manaward";
		case 0x9e: return "convert";
		case 0x9f: return "freeze";
		case 0xa0: return "apocatastasis";
		case 0xa1: return "manawall";
		case 0xa2: return "flare";
		case 0xa3: return "ruin";
		case 0xa4: return "bio";
		case 0xa5: return "summon";
		case 0xa6: return "aetherflow";
		case 0xa7: return "energy drain";
		case 0xa8: return "miasma";
		case 0xa9: return "virus";
		case 0xaa: return "summon ii";
		case 0xab: return "sustain";
		case 0xac: return "ruin ii";
		case 0xad: return "resurrection";
		case 0xae: return "bane";
		case 0xaf: return "eye for an eye";
		case 0xb0: return "rouse";
		case 0xb1: return "miasma ii";
		case 0xb2: return "bio ii";
		case 0xb3: return "shadow flare";
		case 0xb4: return "summon iii";
		case 0xb5: return "fester";
		case 0xb6: return "tri-bind";
		case 0xb7: return "spur";
		case 0xb8: return "enkindle";
		case 0xb9: return "adloquium";
		case 0xba: return "succor";
		case 0xbb: return "leeches";
		case 0xbc: return "sacred soil";
		case 0xbd: return "lustrate";
		case 0xbe: return "physick";
		case 0xbf: return "stoneskin ii";
		case 0xc5: return "shield wall";
		case 0xc6: return "mighty guard";
		case 0xc7: return "last bastion";
		case 0xc8: return "braver";
		case 0xc9: return "bladedance";
		case 0xca: return "final heaven";
		case 0xcb: return "skyshard";
		case 0xcc: return "starstorm";
		case 0xcd: return "meteor";
		case 0xce: return "healing wind";
		case 0xcf: return "breath of the earth";
		case 0xd0: return "pulse of life";
		case 0x137: return "blaze spikes";
		case 0x138: return "ice spikes";
		case 0x156: return "soul drain";
		case 0x17a: return "blood drain";
		case 0x1aa: return "enfire";
		case 0x1ab: return "enblizzard";
		case 0x1ac: return "enaero";
		case 0x1ad: return "enstone";
		case 0x1ae: return "enthunder";
		case 0x1af: return "enwater";
		case 0x1ff: return "sanguine bite";
		case 0x248: return "rotten breath";
		case 0x279: return "gouge";
		case 0x27a: return "shining topaz";
		case 0x27b: return "curl";
		case 0x27c: return "storm";
		case 0x27d: return "gust";
		case 0x27e: return "backdraft";
		case 0x27f: return "downburst";
		case 0x280: return "shining emerald";
		case 0x2ab: return "white breath";
		case 0x2b6: return "immortalize";
		case 0x2d4: return "digest";
		case 0x2df: return "miasma breath";
		case 0x313: return "rock buster";
		case 0x314: return "mountain buster";
		case 0x315: return "earthen ward";
		case 0x316: return "landslide";
		case 0x317: return "earthen fury";
		case 0x318: return "wind blade";
		case 0x319: return "shockwave";
		case 0x31a: return "aerial slash";
		case 0x31b: return "contagion";
		case 0x31c: return "aerial blast";
		case 0x31d: return "crimson cyclone";
		case 0x31e: return "burning strike";
		case 0x31f: return "radiant shield";
		case 0x320: return "flaming crush";
		case 0x321: return "inferno";
		case 0x322: return "embrace";
		case 0x323: return "whispering dawn";
		case 0x324: return "fey covenant";
		case 0x325: return "fey illumination";
		case 0x326: return "embrace-selene";
		case 0x327: return "silent dusk";
		case 0x328: return "fey glow";
		case 0x329: return "fey light";
		case 0x32a: return "fey caress";
		case 0x32b: return "fey wind";
		case 0x331: return "choco strike";
		case 0x332: return "choco guard";
		case 0x333: return "choco kick";
		case 0x334: return "choco drop";
		case 0x335: return "choco blast";
		case 0x336: return "choco rush";
		case 0x337: return "choco beak";
		case 0x338: return "choco slash";
		case 0x339: return "choco medica";
		case 0x33a: return "choco surge";
		case 0x33b: return "choco cure";
		case 0x33c: return "choco regen";
		case 0x35b: return "ice spikes";
		case 0x3dc: return "drain touch";
		case 0x3de: return "bang toss";
		case 0x437: return "canker";
		case 0x442: return "moldy sneeze";
		case 0x4bc: return "disseminate";
		case 0x4ce: return "leech";
		case 0x4da: return "death sentence";
		case 0x59c: return "blessing of light";
		case 0x5cd: return "lunatic voice";
		case 0x5fe: return "infernal fetters";
		case 0x631: return "attunement";
		case 0x64a: return "blood sword";
		case 0x67b: return "putrid cloud";
		case 0x72c: return "bravery";
		case 0x7da: return "lunar dynamo";
		case 0x80a: return "pom cure";
		case 0x874: return "Mantle of the Whorl";
		case 0x875: return "Veil of the Whorl";
		case 0x89c: return "ripe banana";
		case 0x8c0: return "spinning edge";
		case 0x8c1: return "shade shift";
		case 0x8c2: return "gust slash";
		case 0x8c3: return "kiss of the wasp";
		case 0x8c4: return "mutilate";
		case 0x8c5: return "hide";
		case 0x8c6: return "assassinate";
		case 0x8c7: return "throwing dagger";
		case 0x8c8: return "mug";
		case 0x8c9: return "goad";
		case 0x8ca: return "sneak attack";
		case 0x8cb: return "dancing edge";
		case 0x8cc: return "kiss of the viper";
		case 0x8ce: return "death blossom";
		case 0x8cf: return "aeoilian edge";
		case 0x8d0: return "jugulate";
		case 0x8d1: return "shadow fang";
		case 0x8d2: return "trick attack";
		case 0x8d3: return "ten";
		case 0x8d4: return "ninjutsu";
		case 0x8d5: return "chi";
		case 0x8d6: return "shukuchi";
		case 0x8d7: return "jin";
		case 0x8d8: return "kassatsu";
		case 0x8d9: return "fuma shuriken";
		case 0x8da: return "katon";
		case 0x8db: return "raiton";
		case 0x8dc: return "hyoton";
		case 0x8dd: return "huton";
		case 0x8de: return "doton";
		case 0x8df: return "suiton";
		case 0x8e0: return "rabbit medium";
		case 0x923: return "drain-mob";
		case 0x943: return "Mini";
		case 0x964: return "head over heals";
		case 0x986: return "aura curtain";
		case 0x993: return "frost blade";
		case 0x9ff: return "lunar dynamo 9ff";
		case 0xb30: return "rook autoturret";
		case 0xb31: return "bishop autoturret";
		case 0xb32: return "split shot";
		case 0xb33: return "reload";
		case 0xb34: return "slug shot";
		case 0xb35: return "lead shot";
		case 0xb36: return "spread shot";
		case 0xb37: return "grenado shot";
		case 0xb38: return "hot shot";
		case 0xb39: return "clean shot";
		case 0xb3a: return "gauss round";
		case 0xb3b: return "heartbreak";
		case 0xb3c: return "reassemble";
		case 0xb3d: return "leg graze";
		case 0xb3e: return "wildfire";
		case 0xb3f: return "quick reload";
		case 0xb40: return "gauss barrel";
		case 0xb41: return "rapid fire";
		case 0xb42: return "rend mind";
		case 0xb43: return "suppressive fire";
		case 0xb44: return "foot graze";
		case 0xb45: return "hypercharge";
		case 0xb46: return "head graze";
		case 0xb47: return "dismantle";
		case 0xb48: return "blank";
		case 0xb49: return "promotion";
		case 0xb4a: return "ricochet";
		case 0xb4b: return "volley fire";
		case 0xb4c: return "aether mortar";
		case 0xb91: return "bluefire";
		case 0xcb1: return "Mini - WoD";
		case 0xd0e: return "marrow drain";
		case 0xd5b: return "Aetherial Distribution";
		case 0xd9f: return "turret retrieval";
		case 0xdd2: return "goring blade";
		case 0xdd3: return "royal authority";
		case 0xdd4: return "divine veil";
		case 0xdd5: return "clemency";
		case 0xdd6: return "sheltron";
		case 0xdd7: return "tornado kick";
		case 0xdd8: return "purification";
		case 0xdd9: return "elixir field";
		case 0xdda: return "meditation";
		case 0xddb: return "the forbidden chakra";
		case 0xddc: return "deliverance";
		case 0xddd: return "fell cleave";
		case 0xdde: return "decimate";
		case 0xddf: return "raw intuition";
		case 0xde0: return "equilibrium";
		case 0xde1: return "blood of the dragon";
		case 0xde2: return "fang and claw";
		case 0xde3: return "geirskogul";
		case 0xde4: return "wheeling thrust";
		case 0xde5: return "battle litany";
		case 0xde6: return "empyreal arrow";
		case 0xde7: return "the wanderer's minuet";
		case 0xde8: return "iron jaws";
		case 0xde9: return "the warden's paean";
		case 0xdea: return "sidewinder";
		case 0xdeb: return "armor crush";
		case 0xdec: return "shadewalker";
		case 0xded: return "smoke screen";
		case 0xdee: return "dream within a dream";
		case 0xdef: return "duality";
		case 0xdf0: return "stone iii";
		case 0xdf1: return "asylum";
		case 0xdf2: return "tetragrammaton";
		case 0xdf3: return "assize";
		case 0xdf4: return "aero iii";
		case 0xdf5: return "ley lines";
		case 0xdf6: return "sharpcast";
		case 0xdf7: return "enochian";
		case 0xdf8: return "blizzard iv";
		case 0xdf9: return "fire iv";
		case 0xdfa: return "painflare";
		case 0xdfb: return "ruin iii";
		case 0xdfc: return "tri-disaster";
		case 0xdfd: return "dreadwyrm trance";
		case 0xdfe: return "deathflare";
		case 0xdff: return "indomitability";
		case 0xe00: return "broil";
		case 0xe01: return "deployment tactics";
		case 0xe02: return "emergency tactics";
		case 0xe03: return "dissipation";
		case 0xe04: return "charged volley fire";
		case 0xe05: return "charged aether mortar";
		case 0xe06: return "draw";
		case 0xe07: return "royal road";
		case 0xe08: return "spread";
		case 0xe09: return "redraw";
		case 0xe0a: return "benefic";
		case 0xe0b: return "aspected benefic";
		case 0xe0c: return "malefic";
		case 0xe0d: return "stella";
		case 0xe0e: return "malefic ii";
		case 0xe0f: return "combust";
		case 0xe10: return "helios";
		case 0xe11: return "aspected helios";
		case 0xe12: return "exalted detriment";
		case 0xe13: return "ascend";
		case 0xe14: return "diurnal sect";
		case 0xe15: return "nocturnal sect";
		case 0xe16: return "lightspeed";
		case 0xe17: return "luminiferous aether";
		case 0xe18: return "combust ii";
		case 0xe19: return "disable";
		case 0xe1a: return "benefic ii";
		case 0xe1b: return "time dilation";
		case 0xe1c: return "synastry";
		case 0xe1d: return "collective unconscious";
		case 0xe1e: return "essential dignity";
		case 0xe1f: return "gravity";
		case 0xe20: return "celestial opposition";
		case 0xe21: return "hard slash";
		case 0xe22: return "shadowskin";
		case 0xe23: return "spinning slash";
		case 0xe24: return "scourge";
		case 0xe25: return "unleash";
		case 0xe26: return "low blow";
		case 0xe27: return "syphon strike";
		case 0xe28: return "unmend";
		case 0xe29: return "blood weapon";
		case 0xe2a: return "reprisal";
		case 0xe2b: return "power slash";
		case 0xe2c: return "darkside";
		case 0xe2d: return "grit";
		case 0xe2e: return "dark dance";
		case 0xe2f: return "blood price";
		case 0xe30: return "souleater";
		case 0xe31: return "dark passenger";
		case 0xe32: return "dark mind";
		case 0xe33: return "dark arts";
		case 0xe34: return "shadow wall";
		case 0xe35: return "delirium";
		case 0xe36: return "living dead";
		case 0xe37: return "salted earth";
		case 0xe38: return "plunge";
		case 0xe39: return "abyssal drain";
		case 0xe3a: return "sole survivor";
		case 0xe3b: return "carve and spit";
		case 0xe80: return "dragonfly avatar";
		case 0xe81: return "scorpion avatar";
		case 0xe82: return "beetle avatar";
		case 0xeb1: return "warlord shell";
		case 0xfdc: return "explosion";
		case 0x108e: return "big shot";
		case 0x108f: return "desperado";
		case 0x1090: return "land walker";
		case 0x1091: return "dark force";
		case 0x1092: return "dragonsong dive";
		case 0x1093: return "chimatsuri";
		case 0x1094: return "sagittarius arrow";
		case 0x1095: return "satellite beam";
		case 0x1096: return "teraflare";
		case 0x1097: return "angel feathers";
		case 0x1098: return "astral stasis";
		case 0x10a6: return "form shift";
		case 0x1131: return "the balance";
		case 0x1132: return "the bole";
		case 0x1133: return "the arrow";
		case 0x1134: return "the spear";
		case 0x1135: return "the ewer";
		case 0x1136: return "the spire";
		case 0x11c7: return "potion";
		case 0x11c8: return "hi-potion";
		case 0x11c9: return "mega-potion";
		case 0x11ca: return "x-potion";
		case 0x11cb: return "vial of ether";
		case 0x11cc: return "vial of hi-ether";
		case 0x11cd: return "vial of mega-ether";
		case 0x11ce: return "vial of x-ether";
		case 0x11cf: return "bottle of elixir";
		case 0x11d0: return "bottle of hi-elixir";
		case 0x11e8: return "flask of potent poison potion";
		case 0x128b: return "bloodstain";
		case 0x1326: return "bodyhurt breakblock";
		case 0x1327: return "brainhurt breakblock";
		case 0x132c: return "meltyspume";
		case 0x13cc: return "sanguine bite";
		case 0x13cf: return "brainshaker";
		case 0x1598: return "guzzle";
		case 0x16d3: return "bodyhurt breakblock";
		case 0x1731: return "seed of the sky";
		case 0x1734: return "retribution";
		case 0x1cd6: return "intervention";
		case 0x1cd7: return "requiescat";
		case 0x1cd8: return "holy spirit";
		case 0x1cd9: return "passage of arms";
		case 0x1cda: return "onslaught";
		case 0x1cdb: return "upheaval";
		case 0x1cdc: return "shake it off";
		case 0x1cdd: return "inner release";
		case 0x1cde: return "delirium";
		case 0x1cdf: return "quietus";
		case 0x1ce0: return "bloodspiller";
		case 0x1ce1: return "the blackest night";
		case 0x1ce2: return "riddle of earth";
		case 0x1ce3: return "riddle of fire";
		case 0x1ce4: return "brotherhood";
		case 0x1ce5: return "sonic thrust";
		case 0x1ce6: return "dragon sight";
		case 0x1ce7: return "mirage dive";
		case 0x1ce8: return "nastrond";
		case 0x1ce9: return "hellfrog medium";
		case 0x1cea: return "bhavacakra";
		case 0x1ceb: return "ten chi jin";
		case 0x1ced: return "troubador";
		case 0x1cee: return "caustic bite";
		case 0x1cef: return "stormbite";
		case 0x1cf0: return "nature's minne";
		case 0x1cf1: return "refulgent arrow";
		case 0x1cf2: return "cooldown";
		case 0x1cf6: return "barrel stabilizer";
		case 0x1cf7: return "rook overdrive";
		case 0x1cf8: return "rook overload";
		case 0x1cf9: return "bishop overload";
		case 0x1cfa: return "flamethrower";
		case 0x1cfb: return "between the lines";
		case 0x1cfc: return "thunder iv";
		case 0x1cfd: return "triplecast";
		case 0x1cfe: return "foul";
		case 0x1cff: return "aetherpact";
		case 0x1d00: return "bio iii";
		case 0x1d01: return "miasma iii";
		case 0x1d02: return "ruin iv";
		case 0x1d03: return "summon bahamut";
		case 0x1d04: return "wyrmweave";
		case 0x1d05: return "enkindle bahamut";
		case 0x1d06: return "thin air";
		case 0x1d07: return "stone iv";
		case 0x1d08: return "divine benison";
		case 0x1d09: return "plenary indulgence";
		case 0x1d0a: return "Excogitation";
		case 0x1d0b: return "Broil II";
		case 0x1d0c: return "Chain Strategem";
		case 0x1d0d: return "Aetherpact ";
		case 0x1d0e: return "Fey Union";
		case 0x1d0f: return "earthly star";
		case 0x1d10: return "stellar burst";
		case 0x1d11: return "stellar explosion";
		case 0x1d12: return "malefic iii";
		case 0x1d13: return "minor arcana";
		case 0x1d14: return "lord of crowns";
		case 0x1d15: return "lady of crowns";
		case 0x1d18: return "sleeve draw";
		case 0x1d19: return "akh morn";
		case 0x1d1a: return "devotion";
		case 0x1d35: return "hakaze";
		case 0x1d36: return "jinpu";
		case 0x1d37: return "shifu";
		case 0x1d38: return "yukikaze";
		case 0x1d39: return "gekko";
		case 0x1d3a: return "kasha";
		case 0x1d3b: return "fuga";
		case 0x1d3c: return "mangetsu";
		case 0x1d3d: return "oka";
		case 0x1d3e: return "enpi";
		case 0x1d3f: return "midare setsugekka";
		case 0x1d40: return "tenka goken";
		case 0x1d41: return "higanbana";
		case 0x1d42: return "hissatsu: shinten";
		case 0x1d43: return "hissatsu: yaten";
		case 0x1d44: return "hissatsu: gyoten";
		case 0x1d46: return "hissatsu: kaiten";
		case 0x1d47: return "hagakure";
		case 0x1d48: return "hissatsu: guren";
		case 0x1d49: return "meditate";
		case 0x1d4a: return "third eye";
		case 0x1d4b: return "meikyo shisui";
		case 0x1d4c: return "ageha";
		case 0x1d4d: return "hissatsu: seigan";
		case 0x1d4e: return "merciful eyes";
		case 0x1d4f: return "jolt";
		case 0x1d50: return "riposte";
		case 0x1d51: return "verthunder";
		case 0x1d52: return "corps-a-corps";
		case 0x1d53: return "veraero";
		case 0x1d54: return "tether";
		case 0x1d55: return "scatter";
		case 0x1d56: return "verfire";
		case 0x1d57: return "verstone";
		case 0x1d58: return "zwerchhau";
		case 0x1d59: return "moulinet";
		case 0x1d5a: return "vercure";
		case 0x1d5b: return "displacement";
		case 0x1d5c: return "redoublement";
		case 0x1d5d: return "fleche";
		case 0x1d5e: return "acceleration";
		case 0x1d5f: return "contre sixte";
		case 0x1d60: return "embolden";
		case 0x1d61: return "manafication";
		case 0x1d62: return "impact";
		case 0x1d63: return "verraise";
		case 0x1d64: return "jolt ii";
		case 0x1d65: return "verflare";
		case 0x1d66: return "verholy";
		case 0x1d67: return "enchanted riposte";
		case 0x1d68: return "enchanted zwerchhau";
		case 0x1d69: return "enchanted redoublement";
		case 0x1d6a: return "enchanted moulinet";
		case 0x1d6b: return "rampart";
		case 0x1d6c: return "convalescence";
		case 0x1d6d: return "provoke";
		case 0x1d6e: return "awareness";
		case 0x1d6f: return "reprisal";
		case 0x1d70: return "anticipation";
		case 0x1d71: return "shirk";
		case 0x1d72: return "interject";
		case 0x1d73: return "ultimatum";
		case 0x1d74: return "low blow";
		case 0x1d75: return "second wind";
		case 0x1d76: return "bloodbath";
		case 0x1d77: return "goad";
		case 0x1d78: return "invigorate";
		case 0x1d79: return "diversion";
		case 0x1d7a: return "true north";
		case 0x1d7b: return "crutch";
		case 0x1d7c: return "arm's length";
		case 0x1d7d: return "feint";
		case 0x1d7e: return "palisade";
		case 0x1d7f: return "head graze";
		case 0x1d80: return "arm graze";
		case 0x1d81: return "foot graze";
		case 0x1d82: return "leg graze";
		case 0x1d83: return "tactician";
		case 0x1d84: return "refresh";
		case 0x1d85: return "peloton";
		case 0x1d86: return "break";
		case 0x1d87: return "surecast";
		case 0x1d88: return "addle";
		case 0x1d89: return "swiftcast";
		case 0x1d8a: return "lucid dreaming";
		case 0x1d8b: return "apocatastasis";
		case 0x1d8c: return "drain";
		case 0x1d8d: return "mana shift";
		case 0x1d8e: return "erase";
		case 0x1d8f: return "cleric stance";
		case 0x1d90: return "esuna";
		case 0x1d91: return "eye for an eye";
		case 0x1d92: return "largesse";
		case 0x1d93: return "rescue";
		case 0x1d94: return "protect";
		case 0x1eb5: return "doom of the living";
		case 0x1eb6: return "vermillion scourge";
		case 0x1eb7: return "leg sweep";
		case 0x1eb8: return "earth tackle";
		case 0x1eb9: return "wind tackle";
		case 0x1eba: return "fire tackle";
		case 0x1ebb: return "iaijutsu";
		case 0x1ebc: return "riddle of wind";
		case 0x1ebd: return "Dissolve Union";
		case 0x2084: return "stellar detonation";
		case 0x228a: return "pitch perfect";
		case 0x2290: return "heated split shot";
		case 0x2291: return "heated slug shot";
		case 0x2292: return "heated clean shot";
		case 0x2337: return "remove barrel";
		case 0xf540a: return "x-potion ищ";
		case 0xf540e: return "vial of x-ether ищ";
		case 0xf540f: return "bottle of elixir ищ";
		case 0xf5428: return "flask of potent poison potion ищ";

	}
	char res[256];
	sprintf(res, "(skill id %x)", skillid);
	return res;
}
